- name: Get Brews to install
  shell: cat ./ansible/roles/brew-base/files/brewitems
  register: brewitems

- name: Install each item
  shell: echo  "Installing {{ item }}"
  with_items: "{{brewitems.stdout_lines}}"

