---
- name: Get Brews to install
  shell: cat ./ansible/roles/brew-base/files/brewitems
  register: brewitems

- name: Install each item
  homebrew: name="{{ item }}" state="present"
  with_items: "{{brewitems.stdout_lines}}"

- name: Get Taps
  shell: cat ./ansible/roles/brew-base/files/taps
  register: Tapitems

- name: Tap the Casks
  homebrew_tap: name="{{ item }}" state="present"
  with_items: "{{ Tapitems.stdout_lines }}"

- name: Get the Casks
  shell: cat ./ansible/roles/brew-base/files/brewcaskitems
  register: caskitems
  
- name: Install the Casks
  homebrew_cask: name="{{ item }}" state="present"
  with_items: "{{ caskitems.stdout_lines }}"
